<script>
  let { data } = $props();
</script>

<header class="site-header">
  <span class="brand">notext</span>
  <span class="tagline">testing</span>
</header>

<main class="page doc-page">
  <div class="card">
    <h1>{data.doc.title || "Untitled"}</h1>
    <p class="muted">Choose a test part:</p>

    <a class="test-part" href="/doc/{data.id}/test/understanding">
      <div>
        <strong>Understanding test</strong>
        <p class="muted">
          A quiz about the text: multiple choice, fill-the-gap and open
          questions — generated by an LLM and stored with the document.
        </p>
      </div>
      <span class="begin-arrow">→</span>
    </a>

    <p class="muted">More test parts coming soon.</p>

    <div class="actions">
      <a class="btn" href="/doc/{data.id}/read">Back</a>
      <a class="btn" href="/doc/{data.id}/test/result">Results</a>
    </div>
  </div>
</main>

<footer class="site-footer">
  <span>notext · pages are rendered on the server</span>
</footer>
